import Head from 'next/head'
import {
  Box,
  Heading,
  Container,
  Card,
  CardBody,
  CardHeader,
  CardFooter,
  Grid,
} from '@chakra-ui/react'
import { LoginButton } from '../components/login-button'
import { useSession } from 'next-auth/react'

export default function Home() {
  const { data: session } = useSession()
  return (
    <>
      <Head>
        <title>Hello Slack Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        alignItems="center"
        justifyItems="center"
        templateRows="auto 1fr auto"
        h="100vh"
      >
        <Heading>Hello Slack Auth!</Heading>

        <Container>
          <Card>
            <CardHeader>Session status</CardHeader>
            <CardBody>session: {JSON.stringify(session)}</CardBody>
            <CardFooter>
              <LoginButton />
            </CardFooter>
          </Card>
        </Container>

        <Box>hogehoge</Box>
      </Grid>
    </>
  )
}
