import Head from 'next/head'
import { Box } from '@chakra-ui/react'
import { LoginButton } from '../components/login-button'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box w="120" mt="4" mx="2" p="4" bgColor="red">
          Hello!
        </Box>
        <LoginButton />
      </main>
    </>
  )
}
